CREATE TABLE "store_profiles" (
	"id" smallint PRIMARY KEY DEFAULT 1 NOT NULL,
	"trade_name" varchar(200) NOT NULL,
	"legal_name" varchar(200) NOT NULL,
	"tax_identifier" varchar(80) NOT NULL,
	"address_line_1" varchar(250) NOT NULL,
	"address_line_2" varchar(250),
	"address_city" varchar(120) NOT NULL,
	"address_region" varchar(120),
	"address_postal_code" varchar(32),
	"address_country_code" varchar(2) NOT NULL,
	"contact_email" varchar(254),
	"contact_phone" varchar(40),
	"logo_storage_key" varchar(512),
	"logo_url" varchar(2048),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "store_profiles_singleton" CHECK ("store_profiles"."id" = 1),
	CONSTRAINT "store_profiles_trade_name_not_blank" CHECK (btrim("store_profiles"."trade_name") <> ''),
	CONSTRAINT "store_profiles_legal_name_not_blank" CHECK (btrim("store_profiles"."legal_name") <> ''),
	CONSTRAINT "store_profiles_tax_identifier_not_blank" CHECK (btrim("store_profiles"."tax_identifier") <> ''),
	CONSTRAINT "store_profiles_address_line_1_not_blank" CHECK (btrim("store_profiles"."address_line_1") <> ''),
	CONSTRAINT "store_profiles_address_city_not_blank" CHECK (btrim("store_profiles"."address_city") <> ''),
	CONSTRAINT "store_profiles_address_country_code_format" CHECK ("store_profiles"."address_country_code" ~ '^[A-Z]{2}$'),
	CONSTRAINT "store_profiles_address_line_2_not_blank" CHECK ("store_profiles"."address_line_2" is null or btrim("store_profiles"."address_line_2") <> ''),
	CONSTRAINT "store_profiles_address_region_not_blank" CHECK ("store_profiles"."address_region" is null or btrim("store_profiles"."address_region") <> ''),
	CONSTRAINT "store_profiles_address_postal_code_not_blank" CHECK ("store_profiles"."address_postal_code" is null or btrim("store_profiles"."address_postal_code") <> ''),
	CONSTRAINT "store_profiles_contact_email_not_blank" CHECK ("store_profiles"."contact_email" is null or btrim("store_profiles"."contact_email") <> ''),
	CONSTRAINT "store_profiles_contact_phone_not_blank" CHECK ("store_profiles"."contact_phone" is null or btrim("store_profiles"."contact_phone") <> ''),
	CONSTRAINT "store_profiles_logo_reference_complete" CHECK (("store_profiles"."logo_storage_key" is null and "store_profiles"."logo_url" is null) or ("store_profiles"."logo_storage_key" is not null and btrim("store_profiles"."logo_storage_key") <> '' and "store_profiles"."logo_url" is not null and btrim("store_profiles"."logo_url") <> ''))
);
